name: exercise_e5
description: Exercise E5
version: 1.0.0
homepage: https://www.ntnu.edu/studies/courses/IDATA2503

environment:
  sdk: '>=2.17.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
